#!/bin/bash
#PBS -N triptych_drifting_newsvendor
#PBS -J 0-99
#PBS -l select=1:ncpus=1:mem=8gb
#PBS -l walltime=09:00:00

module load tools/prod
module load Julia/1.11.6-linux-x86_64
module load Gurobi/11.0.0-GCCcore-12.3.0

cd "$HOME/dont-look-back-in-anger" || exit 1

export JULIA_CPU_TARGET="${JULIA_CPU_TARGET:-generic}"

julia --startup-file=no \
      --project=. \
      --threads=1 \
      generate-train-and-test-multi-item-triptych-drifting-newsvendor-data.jl
